# DELETE http://localhost:2000/api/v1/transaction/65cf8e30d5fc157d6eaa58e1
GET http://localhost:2000/api/v1/transactions/65cf86b3f1c0f913afddfc3d

# PUT http://localhost:2000/api/v1/transaction
# Content-Type: application/json
#
# {
#     "user": "65cf86b3f1c0f913afddfc3d",
#     "id": "65cf8e30d5fc157d6eaa58e9",
#     "desc": "Dummy update 1"
# }

